version: '3.8'

services:
  cloudflared-home:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel-home
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared/home:/etc/cloudflared
    extra_hosts:
      - "host.docker.internal:host-gateway"
